# Generated by Django 2.2.7 on 2019-12-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='processor',
            field=models.CharField(choices=[('snapdragon', 'Snapdragon'), ('mediatek', 'Mediatek')], max_length=100),
        ),
    ]
