# Generated by Django 2.2.7 on 2019-12-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20191205_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='processor',
            field=models.CharField(choices=[('intel', 'Intel'), ('amd Raedon', 'AMD Raedon')], max_length=100),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='processor',
            field=models.CharField(choices=[('mediatek', 'Mediatek'), ('snapdragon', 'Snapdragon')], max_length=100),
        ),
    ]
